# Generated by Django 4.2.5 on 2023-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_upload_date_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='screenshot',
            field=models.ImageField(blank=True, default='static/no_image.jpg', upload_to='screenshots/'),
        ),
    ]
