# Generated by Django 4.2.5 on 2023-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='detected_video',
            field=models.FileField(blank=True, upload_to='detected_videos/'),
        ),
    ]
